USER_TEXTFIELD_MAX_LENGTH = 150

TAG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128

MEASUREMENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256

MIN_COOKING_TIME = 1

MAX_COOKING_TIME = 32000

MIN_INGREDIENT_VALUE = 1

MAX_INGREDIENT_VALUE = 32000

SHORT_LINK_LENGTH = 128
