# Generated by Django 3.2.3 on 2024-08-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': '%(app_label)s_%(class)s', 'verbose_name': 'Избранное'},
        ),
    ]
