# Generated by Django 3.2.3 on 2024-07-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredients_recipe_ingridients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='RecipeIngridients',
            new_name='RecipeIngredients',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredients',
            name='unique_recipe_ingridient',
        ),
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingridient',
            new_name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredients', to='recipes.Ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
    ]
