# Generated by Django 3.2.3 on 2024-08-25 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_shoppingcart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть не меньше 1'), django.core.validators.MaxValueValidator(32000, message='Количество должно быть не больше 32000')], verbose_name='Количество'),
        ),
    ]
